name: Deploy to Develop
on:
  push:
    branches:
      - develop
      - feature/*
  workflow_dispatch:

jobs:
  trivyscan:
    name: Run Trivy vulnerability scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker dev image
        run: |
          cd app/
          docker build -t hadronp/ubuntu-flask:dev-${GITHUB_SHA::7} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: hadronp/ubuntu-flask:dev-${GITHUB_SHA::7}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
      
      